.PHONY: stats check-stats cases-manifest

# Regenerate cases/MANIFEST.txt after adding or removing a case. The manifest
# pins the logical corpus so a case cannot leave it without a visible diff;
# runner/corpus_manifest_test.go asserts the two agree in both directions.
cases-manifest:
	cd runner && go test . -run 'TestCorpus' -update-manifest

# Print canonical stats from test cases.
# The total comes from the committed manifest, which is generated by the same
# loaders the runner uses. Verdicts include the mcp-drift case.yaml.
stats:
	@echo "# agent-egress-bench stats"
	@test -f cases/MANIFEST.txt || { echo "stats: FAIL - missing cases/MANIFEST.txt; run 'make cases-manifest'"; exit 1; }
	@echo "cases_total: $$(awk 'NF { count++ } END { print count + 0 }' cases/MANIFEST.txt)"
	@echo "categories: $$(find cases -mindepth 1 -maxdepth 1 -type d | wc -l)"

# Fail when any tracked document's canonical current-corpus count no longer
# matches the manifest. Current totals use the phrase "N logical cases across
# M categories"; historical release notes deliberately use different prose.
check-stats:
	@test -f cases/MANIFEST.txt || { echo "check-stats: FAIL - missing cases/MANIFEST.txt; run 'make cases-manifest'"; exit 1; }
	@actual=$$(awk 'NF { count++ } END { print count + 0 }' cases/MANIFEST.txt); \
	claims=$$(git grep -nE '[0-9]+ logical cases across [0-9]+ categories' -- '*.md' || true); \
	if [ -z "$$claims" ]; then \
		echo "check-stats: FAIL - no canonical 'N logical cases across M categories' claim found in tracked Markdown"; \
		echo "  fix: add the current corpus total from 'make stats' to a tracked document"; \
		exit 1; \
	fi; \
	mismatches=$$(printf '%s\n' "$$claims" | while IFS=: read -r file line text; do \
		stated=$$(printf '%s\n' "$$text" | grep -oE '[0-9]+ logical cases' | head -1 | cut -d' ' -f1); \
		if [ "$$stated" != "$$actual" ]; then \
			printf '%s:%s advertises %s logical cases, manifest has %s\n' "$$file" "$$line" "$$stated" "$$actual"; \
		fi; \
	done); \
	if [ -n "$$mismatches" ]; then \
		echo "check-stats: FAIL - stale canonical corpus count claim(s):"; \
		printf '%s\n' "$$mismatches"; \
		echo "  fix: run 'make stats', update every listed claim, then run 'make check-stats'"; \
		exit 1; \
	fi; \
	claim_count=$$(printf '%s\n' "$$claims" | wc -l | tr -d ' '); \
	echo "check-stats: OK ($$actual logical cases; $$claim_count tracked canonical claim(s) agree)"
